# -*- coding: utf-8 -*-
# 一些背景色及前景色，供不同的标签进行使用
# bg: background-color
# fg: foreground-color
# '#ffff1a','#3399ff','#4dff4d','#ff3300','#ff3399','#cc33ff','#6600ff',
# '#66a3ff','#0086b3','#4da6ff','#F5F5DC'
# color_mapping = [
#     {'bg': '#3399ff',
#      'fg': 'black'},
#     {'bg': '#4dff4d',
#      'fg': 'black'},
#     {'bg': '#ffff1a',
#      'fg': 'black'},
#     {'bg': '#FF1493',
#      'fg': 'white'},
#     {'bg': '#ff3399',
#      'fg': 'white'},
#     {'bg': '#cc33ff',
#      'fg': 'white'},
#     {'bg': '#6600ff',
#      'fg': 'white'},
#     {'bg': '#66a3ff',
#      'fg': 'black'},
#     {'bg': '#0086b3',
#      'fg': 'white'},
#     {'bg': '#4da6ff',
#      'fg': 'white'},
#     {'bg': '#00FF00',
#      'fg': 'black'},
#     {'bg': '#00FF00',
#      'fg': 'black'},
#     {'bg': '#00FF00',
#      'fg': 'black'},
#     {'bg': '#00FF00',
#      'fg': 'white'},
#     {'bg': '#00FF00',
#      'fg': 'white'},
#     {'bg': '#00FF00',
#      'fg': 'white'},
#     {'bg': '#00FF00',
#      'fg': 'white'},
#     {'bg': '#00FF00',
#      'fg': 'black'},
#     {'bg': '#00FF00',
#      'fg': 'white'},
#     {'bg': '#00FF00',
#      'fg': 'white'},
#     {'bg': '#3399ff',
#      'fg': 'black'},
#     {'bg': '#00FFFF',
#      'fg': 'black'},
#     {'bg': '#ffff1a',
#      'fg': 'black'},
#     {'bg': '#FF1493',
#      'fg': 'white'},
#     {'bg': '#FF8C00',
#      'fg': 'white'},
#     {'bg': '#cc33ff',
#      'fg': 'white'},
#     {'bg': '#f5f5dc',
#      'fg': 'black'}
# ]


color_mapping = [
    {'bg': '#00FF00',
     'fg': 'black'},
    {'bg': '#00FF00',
     'fg': 'black'},
    {'bg': '#00FF00',
     'fg': 'black'},
    {'bg': '#00FF00',
     'fg': 'white'},
    {'bg': '#00FF00',
     'fg': 'white'},
    {'bg': '#00FF00',
     'fg': 'white'},
    {'bg': '#00FF00',
     'fg': 'white'},
    {'bg': '#00FF00',
     'fg': 'black'},
    {'bg': '#00FF00',
     'fg': 'white'},
    {'bg': '#00FF00',
     'fg': 'white'},
]

